In [1]:
import torch

In [65]:
torch.fill()

TypeError: fill() received an invalid combination of arguments - got (size=int, value=float, ), but expected one of:
 * (Tensor input, Tensor value)
      didn't match because some of the keywords were incorrect: size
 * (Tensor input, Number value)
      didn't match because some of the keywords were incorrect: size


In [6]:
cov_matrix = torch.diag(torch.full(size=(4,), fill_value=0.5))

In [15]:
mean = torch.tensor([1, 2, 3, 4], dtype=torch.float32)

In [16]:
from torch.distributions import MultivariateNormal

dist = MultivariateNormal(mean, cov_matrix)

In [21]:
action = dist.sample()

In [22]:
log_prob = dist.log_prob(action)

In [28]:
a = action.detach()

In [30]:
a.grad

In [31]:
a = torch.tensor([3,4,4,4])

In [32]:
temp = []

for _ in range(4):
    temp.append(a)

In [33]:
temp

[tensor([3, 4, 4, 4]),
 tensor([3, 4, 4, 4]),
 tensor([3, 4, 4, 4]),
 tensor([3, 4, 4, 4])]

In [38]:
import numpy as np
temp = []

for _ in range(4):
    temp.append(np.array([3, 4, 5, 6]))


In [39]:
temp

[array([3, 4, 5, 6]),
 array([3, 4, 5, 6]),
 array([3, 4, 5, 6]),
 array([3, 4, 5, 6])]

In [40]:
torch.tensor(temp)

/tmp/ipykernel_3252800/2003895991.py:1: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:261.)
  torch.tensor(temp)


tensor([[3, 4, 5, 6],
        [3, 4, 5, 6],
        [3, 4, 5, 6],
        [3, 4, 5, 6]])

In [41]:
torch.as_tensor(temp, dtype=torch.float)

tensor([[3., 4., 5., 6.],
        [3., 4., 5., 6.],
        [3., 4., 5., 6.],
        [3., 4., 5., 6.]])

In [42]:
torch.tensor(temp, dtype=torch.float)

tensor([[3., 4., 5., 6.],
        [3., 4., 5., 6.],
        [3., 4., 5., 6.],
        [3., 4., 5., 6.]])

In [45]:
a = [1,2,3,4,5,6,7,8,9]
temp = [0] * len(a)

In [46]:
temp

[0, 0, 0, 0, 0, 0, 0, 0, 0]

In [51]:
for re_idx in reversed(range(len(a))):
    print(re_idx)
    temp[re_idx] = temp[re_idx + 1] + a[re_idx] if re_idx < len(a) -1 else a[-1]

8
7
6
5
4
3
2
1
0


In [52]:
temp

[45, 44, 42, 39, 35, 30, 24, 17, 9]

In [53]:
a = []

In [54]:
a.insert(1, 3)

In [55]:
a

[3]

In [56]:
a.insert(0, 3)

In [57]:
a

[3, 3]

In [58]:
a.insert(0, 4)

In [59]:
a

[4, 3, 3]

In [60]:
a.insert(2, 5)

In [61]:
a

[4, 3, 5, 3]